### ISSUE TITLE
Delete batch error "Sorry but something went wrong"

### ISSUE THREAD

**Issue by mikeadamo1** [duke-libraries/dul-hydra#1021]
Attempted to delete a batch (batch 50) by clicking on the trash can icon on the batches page.  It timed out after hanging for 10 mins.  I closed browser and logged back in.  Navigated to the batches page again and batch 50 was still present.  Tried to delete it again.  The page hung up for 2 mins then I got a "Sorry but something went wrong"  error.

**Comment by dchandekstark** [comment]
I hope this has been resolved, but if not, please submit a ServiceNow ticket.
