### ISSUE TITLE
Duplicate batch created when browser times out and 'try again' is clicked

### ISSUE THREAD

**Issue by mikeadamo1** [duke-libraries/dul-hydra#1022]
I was preparing to ingest the DSC collection this morning (8:42).  I was at the point where I click the 'Process" link on the batch page so clicked process and moved on to some other work.  When I got back to my computer the page had timed out.  I selected 'try again' (10:35) in the browser and  page timed out again.  When I logged back in and navigated to the Batch Ingest page there was a duplicate batch present.   I assume the duplicate batch was created when I clicked 'try again'?  How do I avoid this duplication in the future?

**Comment by dchandekstark** [comment]
@coblej Is this still an issue?

**Comment by dchandekstark** [comment]
@coblej ping

**Comment by dchandekstark** [comment]
@coblej Has this been resolved now with data-loading-text button? @seanaery

**Comment by dchandekstark** [comment]
@coblej @seanaery ping

**Comment by coblej** [comment]
@dchandekstark Yes, I think this issue has been resolved.
