### ISSUE TITLE
Function to order components

### ISSUE THREAD

**Issue by jt112** [duke-libraries/dul-hydra#1080]
Authorized users should be able to select and save component display order.  For example, I want to be able to display a README file first in a data object.

**Comment by dchandekstark** [comment]
@coblej Are we prepared to take this on as part of the initial (re-)implementation of structural metadata?

**Comment by dchandekstark** [comment]
Please add to Jira if desired.

**Comment by jt112** [comment]
Could you please explain what criteria is being applied to move or close these issues?

**Comment by dchandekstark** [comment]
Moved to Jira.
