### ISSUE TITLE
Add pick list for dcterms:type field

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1209]

**Comment by jt112** [comment]
I suggest going with the DCMI Type Vocabulary at http://dublincore.org/documents/dcmi-terms/ that Jim suggested in email.  For requests for more specific type values I'd ask for some explanation about why the exisiting values are inadequate and generally lean toward more general terms, like still image, over more specific terms like black and white photograph, which could perhaps be recorded elsewhere in metadata.

**Comment by dchandekstark** [comment]
Need input from @maggiedickson

**Comment by maggiedickson** [comment]
Thanks for looping me in, @dchandekstark. Yes - this field should be limited to the DCMI type values. More specific values should go in the dc:format field.

**Comment by coblej** [comment]
@maggiedickson @dchandekstark Since this has previously been a free-text field, we will likely need to figure out how to deal with existing values that aren't DCMI type values.

**Comment by maggiedickson** [comment]
@coblej @dchandekstark Yes - I generally need to figure out how to either remediate the existing DDR metadata to our specs (or figure out what can go unremediated).

**Comment by dchandekstark** [comment]
@coblej Yes, and there is the further question of batch ingest and update "validation".

**Comment by dchandekstark** [comment]
It might be good to wrap this into investigating the use of https://github.com/projecthydra-labs/questioning_authority. I see the project is still active, which is good (means it's being used).

**Comment by dchandekstark** [comment]
@maggiedickson Would you create a Jira issue to track this going forward?

**Comment by dchandekstark** [comment]
Moved to Jira.
