### ISSUE TITLE
Rake task to publish / unpublish collection / item / component and its children

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1251]
Given a collection, the task will publish/unpublish the collection, all items, and all their components.
Given an item, the task will publish/unpublish the item and all its components.
Given a component, the task will publish/unpublish the component.

**Comment by dchandekstark** [comment]
Are we not publishing Attachments, if present?

**Comment by coblej** [comment]
@dchandekstark We are not publishing Attachments (or Targets) ... only Collections, Items, and Components.

**Comment by dchandekstark** [comment]
@coblej Do we still need/want this in addition to the button/link in the staff UI?

**Comment by coblej** [comment]
Closing.  No longer needed.
