### ISSUE TITLE
Inappropriate flash message on first access

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1254]
"You need to sign in or sign up before continuing."

I believe this is happening b/c /users/sign_in is redirecting in Apache.  The message is supposed to appear on the sign in page, but ends up appearing on the first page the user lands.

**Comment by dchandekstark** [comment]
@coblej This issue will be resolved if we cut a new release of ddr-models and upgrade dul-hydra to it.

**Comment by coblej** [comment]
@dchandekstark Shall I go ahead and do that?  (I.e., cut a new release of ddr-models, upgrade dul-hydra, and cut a new [hopefully final] rc version of dul-hydra?)

**Comment by coblej** [comment]
Fixed via https://github.com/duke-libraries/ddr-models/issues/113
