### ISSUE TITLE
Move permissions.policy_class to ddr-models ?

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1289]
Should this configuration initialization `config.permissions.policy_class = Collection`be moved from dul-hydra/config/initializers/hydra_config.rb to a comparable initializer in ddr-models?

And, likewise, it's currently in ddr-public/config/initializers/hydra_config.rb.

**Comment by coblej** [comment]
@dchandekstark What do you think?

**Comment by dchandekstark** [comment]
+1

**Comment by dchandekstark** [comment]
Need to create an issue in ddr-models and link it to this one.

**Comment by dchandekstark** [comment]
Cleared milestone as not critcal to v4.0.0.

**Comment by dchandekstark** [comment]
I doubt this is still relevant.

**Comment by coblej** [comment]
The config setting may not be relevant but it's still in the code base.
