### ISSUE TITLE
Batch object attributes post-processing verification

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1306]
Current logic to verify that batch object attributes have been properly applied to repository object is inadequate.  Batch object attributes could contain a sequence of actions of different types (add value, delete specific value, clear values for attributes, clear values for all attributes).  Verification ideally needs to compare the before and after states of the relevant datastreams and verify that the net effect of applying the attributes is correct.  Or else we need to drop this verification altogether.

**Comment by dchandekstark** [comment]
@coblej Still relevant?

**Comment by coblej** [comment]
@dchandekstark Yeah, though I don't think it's a high priority.  I'll move it to Jira.
