### ISSUE TITLE
Empty title in web form should not set title to [""]

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1317]

**Comment by dchandekstark** [comment]
@coblej Any idea if this an actual problem?  I tried creating Item on dev with empty title and it did not do this.

**Comment by coblej** [comment]
@dchandekstark I don't remember the details but I think we saw an object in the repository with the title set to [""] and that's what prompted this issue.  However, if we can't reproduce it ...

**Comment by dchandekstark** [comment]
Can't reproduce on dev.
