### ISSUE TITLE
Strip whitespace from metadata elements?

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1346]
The reality is people copy and paste which frequently unintentionally includes extra whitespace before and/or after the metadata value.  Personally I don't see the purpose of the extra whitespace in *metadata* -- it only creates problems and has no significance.

/cc @coblej @jt112 @laissezfarrell @WinstonAtkins

**Comment by WinstonAtkins** [comment]
@dchandekstark : Makes good sense to me. I imagine that leaving it in could cause sorting/ indexing(?) errors, etc., depending on how white space is 'viewed.' 

/cc @coblej @jt112 @laissezfarrell

**Comment by noahgh221** [comment]
I think it's safe to do this and I can't think of any unintended consequences.

**Comment by maggiedickson** [comment]
Agreed.

**Comment by dchandekstark** [comment]
Moved to Jira.
