### ISSUE TITLE
Simple ingest should provide option to create and enqueue batch

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1358]
Now, simple ingest permits the user to create a pending batch but the user then has to go to the Batches display to enqueue the batch for processing.  Simple ingest should permit a batch to be created and enqueued for processing at the same time.  This option should be available through the interactive prompt and via an option bypassing the interactive prompt.

**Comment by dchandekstark** [comment]
@coblej Close or migrate to JIRA?

**Comment by coblej** [comment]
@dchandekstark Close. Moot point now that Simple Ingest is moving to a web UI.
