### ISSUE TITLE
CatalogController and sorting by identifier broken with ddr-models/develop HEAD

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1359]
Ddr::IndexField::IDENTIFIER was a sortable field and used in the CatalogController for that purpose.  It has been replaced by IDENTIFIER_ALL which is not sortable. Please advise. @coblej

**Comment by coblej** [comment]
Cf. Release Notes for ddr-models ... https://github.com/duke-libraries/ddr-models/releases/tag/untagged-1c852ca2fdf5807292c6 .  Ddr::IndexFields::IDENTIFIER is replaced by either Ddr::IndexFields::LOCAL_ID or Ddr::IndexFields::IDENTIFIER_ALL, depending on whether you need a sortable identifier field or not.
