### ISSUE TITLE
Remove identifier from object summary

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1410]

**Comment by dchandekstark** [comment]
@coblej Do we want to do this in 4.x?

**Comment by coblej** [comment]
@dchandekstark In #1455 , I think we decided to remove it from the object summary and put it on the adminMetadata tab.  That's what I would do.

**Comment by dchandekstark** [comment]
Duplicates #1455

**Comment by dchandekstark** [comment]
This is not a duplicate of #1455; here we're referencing the desc metadata identifier.
