### ISSUE TITLE
Modify Roles view is broken

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1450]
Clicking on Modify on the Roles tab of a collection produces the following error:

08:20:21 INFO:   Rendered application/roles.html.erb within layouts/objects (4.7ms) 
08:20:21 INFO: Completed 500 Internal Server Error in 318ms (ActiveRecord: 0.4ms) 
08:20:21 FATAL: 
ActionView::Template::Error (ArgumentError):
    38: 	    <select name="agent" style="width: 100%" required>
    39: 	      <option value="" disabled>Select a User or Group ...</option>
    40: 	      <optgroup label="GROUPS">
    41: 		<%= options_for_select all_group_options %>
    42: 	      </optgroup>
    43: 	      <optgroup label="USERS">
    44: 		<%= options_for_select all_user_options %>
  app/helpers/application_helper.rb:229:in `all_group_options'
  app/views/application/roles.html.erb:41:in `_app_views_application_roles_html_erb__3187826289971622388_71115300'

**Comment by coblej** [comment]
@dchandekstark This is broken in production (v4.1.0).

**Comment by dchandekstark** [comment]
Resolved by upgrading ddr-models to v2.1.3 via ff2a44b459169030fc623262d7c2634e79bff614
