### ISSUE TITLE
Remove ID from object summary

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1455]
Not sure if there is a replacement, other than perhaps the permanent ID, if present (move from object summary). @coblej

**Comment by coblej** [comment]
@dchandekstark I think it might still be useful to see the Fedora ID from the dul-hydra interface in some way, even if the ID in F4 doesn't appear as useful as the F3 PID.  Perhaps it could be moved to the admin metadata display (non-editable, of course).

**Comment by dchandekstark** [comment]
I’m OK with putting it on the Admin Metadata tab.

**Comment by dchandekstark** [comment]
Cf. #1410
