### ISSUE TITLE
Add original file name to Admin Metadata tab for content-bearing objects

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1456]

**Comment by dchandekstark** [comment]
@coblej Wondering if original filename should be included with Tech Metadata rather than Admin Metadata.

**Comment by coblej** [comment]
@dchandekstark Either place is fine with me.

**Comment by coblej** [comment]
Addressed in https://github.com/duke-libraries/dul-hydra/commit/269f3edd5b37b350f25b07bb9520fa245f511fa1
