### ISSUE TITLE
Add METS file ingest button.

### ISSUE THREAD

**Issue by willsexton** [duke-libraries/dul-hydra#1499]
Include a button that will enable a staff user with the proper permissions to start a METS folder ingest for a collection. This process will be the same one we currently use to update descriptive and structural metadata for items, and soon administrative metadata. It's currently initiated with a rake task, but it will be a frequently run process for staff in DPPS as we're ingesting digital collections into the repository.

**Comment by coblej** [comment]
@willsexton This has been done in the Fedora 4 branch of the staff interface code and will be part of the initial dul_hydra 5.0 version.

**Comment by coblej** [comment]
Addressed in https://github.com/duke-libraries/dul-hydra/commit/5b17e2bce278b3e3c45043e03bd02c32ebe0f287
