### ISSUE TITLE
Web UI collection creation should facilitate (require?) setting of admin set

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1510]
Admin sets are used to group collections (and, I believe, to manage certain display characteristics in the public interface).  I am inclined to require each collection to be assigned to an admin set but even if we don't go that far, I think it should its entry should be facilitated in the web UI collection creation process.

**Comment by coblej** [comment]
@jt112 @dchandekstark What do you think?  Should we require that collections be assigned to an admin set?

**Comment by jt112** [comment]
I do think they should be required.  They play an additional role in repository management by clarifying who has primary responsibility for a collection and its contents.  I agree.

**Comment by dchandekstark** [comment]
I agree in theory but it raises some permissions issues which may point towards promoting AdminSet to a full-fledged repository object.  Also, there is not currently a "default" AdminSet, and none of the current ones are appropriate for that purpose.

**Comment by jt112** [comment]
Does it need to be a repository object?  It can't be a mandatory metadata field on the collection object?  I wouldn't want a default AdminSet value.  If we can't determine who is responsible for content and can't find anyone willing to do so, I'd have to wonder why we were bothering with it.

**Comment by coblej** [comment]
@jt112 @dchandekstark Picking back up on this thread ... I believe the permissions issue that David mentioned above (that might argue for AdminSet's being repository objects) has to do with this: If I have the rights to create a collection, do I have the right to associate it with any existing Admin Set?  Or do we want to restrict the Admin Set's which a given person can associate with a Collection he/she creates?

Actually, now that I think about it, the permissions question is broader than this particular issue, which is about adding a pick list of Admin Set's to the Web UI collection creation form.  Even now, without having a field on the collection creation form, once a user creates a collection, he/she can go to the Admin Metadata tab and associate it with any Admin Set they want to.

So, I guess the question is ... do we want to go ahead and add this field to the collection creation form now, bracketing the permissions question for the time being?  If so, I guess the remaining question is whether it should be required or not?

**Comment by dchandekstark** [comment]
Migrating issue to JIRA.
