### ISSUE TITLE
Batches table has empty column on left side

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1527]
@coblej I assume that's not intentional?

**Comment by coblej** [comment]
@dchandekstark Sometimes it's empty, sometimes not.  If the user can delete the batch, the column has a trashcan icon there, which is a link to the delete action.

**Comment by dchandekstark** [comment]
@coblej OK, it looks weird, but not a big deal.  I'd like to leave the issue open for now.

**Comment by coblej** [comment]
@dchandekstark Yeah, I'm sure there's a better UI way to handle it.  Fine with me to leave it open.  Maybe someday things like this in the staff UI can get some love.
