### ISSUE TITLE
bundler conflict

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1587]
It's an annoyance:

Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub ddr-alerts` to work around a system/bundle conflict.

**Comment by coblej** [comment]
@dchandekstark In researching this issue, I ran across this command: `gem pristine --all`.  Unfortunately, I lost the thread of my research and don't remember exactly what led me to that command ... but running it in my local dul-hydra project directory made the message you cite above go away.
