### ISSUE TITLE
Roles edit form broken

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1595]
Existing roles appear blank.

**Comment by coblej** [comment]
@dchandekstark Giving this one back to you for the time being.  Removing the '.first' from the display fields was easy enough but then, when the edited form is submitted, an "uninitialized constant Ddr::Auth::Roles::DetachedRoleSet" error is thrown here: https://github.com/duke-libraries/dul-hydra/blob/develop/app/controllers/concerns/dul_hydra/controller/repository_behavior.rb#L222 .  I figured you might know better than I what the replacement is for Ddr::Auth::Roles::DetachedRoleSet .
