### ISSUE TITLE
Thumbnail path is broken

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1596]
Occurs on repository-dev-02 with Apache httpd.  Suspect it is related to un-escaped slashes in path.

**Comment by coblej** [comment]
Probably not related to unescaped slashes in path after all.  Here is the error message in the Hydra application log:

12:56:25 INFO: Started GET "/thumbnail/57%2F92%2Fae%2Ffe%2F5792aefe-ad4e-4dd0-8684-8301083b6673" for 10.190.51.6 at 2016-02-11 12:56:25 -0500 
12:56:25 INFO: Processing by ThumbnailController#show as HTML 
12:56:25 INFO:   Parameters: {"id"=>"57/92/ae/fe/5792aefe-ad4e-4dd0-8684-8301083b6673"} 
12:56:25 DEBUG:   User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 2  ORDER BY "users"."id" ASC LIMIT 1 
12:56:25 DEBUG:   Load LDP (142.4ms) https://repostore-dev.lib.duke.edu:8443/fcrepo/rest/prod/57/92/ae/fe/5792aefe-ad4e-4dd0-8684-8301083b6673 Service: 20607620 
12:56:25 INFO: Completed 500 Internal Server Error in 522ms (ActiveRecord: 0.4ms) 
12:56:25 FATAL: 
Net::HTTPBadResponse (wrong status line: "\x15\x03\x03\x00\x02\x02"):
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:41:in `read_status_line'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1378:in `request'
  active-fedora (9.6.2) lib/active_fedora/file/streaming.rb:28:in `block in each'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:853:in `start'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:583:in `start'
  active-fedora (9.6.2) lib/active_fedora/file/streaming.rb:26:in `each'
....

**Comment by dchandekstark** [comment]
Caused by projecthydra/active_fedora#992
