### ISSUE TITLE
Content download is broken

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1598]
Observed on repository-dev-02.

Hydra application log:

13:10:59 INFO: Started GET "/download/89%2F20%2F26%2F74%2F89202674-dc0b-452e-933a-1c01f0713363" for 10.190.51.6 at 2016-02-11 13:10:59 -0500 
13:10:59 INFO: Processing by DownloadsController#show as HTML 
13:10:59 INFO:   Parameters: {"id"=>"89/20/26/74/89202674-dc0b-452e-933a-1c01f0713363"} 
13:10:59 DEBUG:   User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 2  ORDER BY "users"."id" ASC LIMIT 1 
13:11:00 DEBUG:   Load LDP (215.8ms) https://repostore-dev.lib.duke.edu:8443/fcrepo/rest/prod/89/20/26/74/89202674-dc0b-452e-933a-1c01f0713363 Service: 20607620 
13:11:00 INFO: Completed 500 Internal Server Error in 597ms (ActiveRecord: 0.4ms) 
13:11:00 FATAL: 
Net::HTTPBadResponse (wrong status line: "\x15\x03\x03\x00\x02\x02"):
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:41:in `read_status_line'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1378:in `request'
  active-fedora (9.6.2) lib/active_fedora/file/streaming.rb:28:in `block in each'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:853:in `start'
  /home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:583:in `start'
  active-fedora (9.6.2) lib/active_fedora/file/streaming.rb:26:in `each'

**Comment by coblej** [comment]
Cf. https://github.com/duke-libraries/dul-hydra/issues/1596

**Comment by dchandekstark** [comment]
I assume this is also resolved by #1603.

**Comment by coblej** [comment]
@dchandekstark Yes, I think it is resolved.  I was able to use the download link successfully on a couple of Component objects on repo-dev-02.  Closing the issue.
