### ISSUE TITLE
Structural Metadata tab is broken for nested div's

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1634]
need hot fix for dul-hydra v4

**Comment by coblej** [comment]
https://github.com/duke-libraries/dul-hydra/commit/98d0503a5dc65c5e0973a9874db38d8f402b425a provides a kludgey fix (assuming no more than two levels of div's) that probably eliminates the need for a hot fix for dul-hydra v4 ... though this needs a better, more generic solution.

**Comment by dchandekstark** [comment]
@coblej Migrate to JIRA?

**Comment by coblej** [comment]
Closing this in deference to future work on structural metadata
