### ISSUE TITLE
Completed batches should list in descending order (most recent first)

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1644]

**Comment by coblej** [comment]
@dchandekstark Should pending batches also list in descending order or only the completed ones?

**Comment by dchandekstark** [comment]
I guess yes.

**Comment by coblej** [comment]
@dchandekstark Need to clarify "most recent".  Most recently _created_ first or most recently _processed_ first?

**Comment by dchandekstark** [comment]
Hm.  I suppose ideally it could be sorted either way, but for just one I'd pick processed.

**Comment by coblej** [comment]
@dchandekstark Now that I think about it, the current order is whatever CanCan's load_resource does by default, which I guess, from looking at the list, is ascending database ID order.  The easiest thing to do, which I imagine would be at least a 98% solution to this issue, is to call .reverse! on the index instance variable.  If that's acceptable, let's just do that for now.

**Comment by dchandekstark** [comment]
@coblej You should be able to add an `.order` clause to the resource since it's a scope.  Using `.reverse!` (I assume the Array method) will force retrieval and instantiation and is probably not compatible with pagination (should we want to use that).  I doubt that CanCan is applying an explicity ordering, but if it is, you can use `.reorder` or `.reverse_order`.
