### ISSUE TITLE
Index FITS message fields and display in landing pages

### ISSUE THREAD

**Issue by jt112** [duke-libraries/dul-hydra#1650]
Farrell asked for access to validity and well-formedness messages.

**Comment by dchandekstark** [comment]
Is this for the Fedora 4 branch, or also for Fedora 3?

/cc @laissezfarrell

**Comment by laissezfarrell** [comment]
I'd usually say we can wait til F4, but given the potential delay, I'd prefer to see it for F3 too. 

That is, unless doing it twice places an undue burden on development resources.

**Comment by jt112** [comment]
Agreed.

Jim Tuttle
Head, Digital Repository Services
Duke University Libraries
919.613.6831

On Mar 28, 2016, at 15:32, Matthew Farrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd usually say we can wait til F4, but given the potential delay, I'd prefer to see it for F3 too.

That is, unless doing it twice places an undue burden on development resources.

-

**Comment by dchandekstark** [comment]
Resolved in #1674
