### ISSUE TITLE
Add DOI to admin metadata tab

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1658]

**Comment by coblej** [comment]
@jt112 @dchandekstark Should the DOI field be available on the admin metadata tab for all objects or just for items?

**Comment by coblej** [comment]
@jt112 @dchandekstark I also notice that, unless most admin metadata fields, which are defined as single-valued, the DOI is defined as multi-valued.  Is that intentional?  Could an object have multiple DOI's?

**Comment by coblej** [comment]
Based on conversation with Jim Tuttle, DOI should be single-valued.

**Comment by coblej** [comment]
Based on conversation with @jt112 , DOI should be available on admin metadata tab for all objects.
