### ISSUE TITLE
Metadata display doesn't render line breaks

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1660]
So you can't see them. :)

**Comment by seanaery** [comment]
@dchandekstark I think it's still unclear whether we need to display line breaks for item metadata. For collection show pages, though, what we're doing (currently on develop branch) is applying special display for the abstract & description fields outside of the standard metadata section. 

![screen shot 2016-04-22 at 2 21 31 pm](https://cloud.githubusercontent.com/assets/3933756/14750992/b3b5ec4c-0895-11e6-9cd1-d57abeaa5c80.png)

**Comment by dchandekstark** [comment]
@seanaery What I mean is, we need to be able to see in the staff UI that the line breaks are there.  Currently we can't.

**Comment by seanaery** [comment]
@dchandekstark Ah, now I see... we're on dul-hydra here :-)
