### ISSUE TITLE
Folder ingest ability is broken

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1698]

**Comment by coblej** [comment]
As it turns out, I don't think this is broken after all.  I think the source of the problem observed during user testing is that the app was not reloaded after correcting the folder_ingest.yml file.

**Comment by dchandekstark** [comment]
That makes sense. :)

**Comment by mikeadamo1** [comment]
I signed out and closed my browser.  After logging in the folder ingest link is available.  Thanks!

**Comment by coblej** [comment]
Not really a bug.
