### ISSUE TITLE
Role grant form does not reset properly

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1710]
After using the "Grant Role" modal form once, the agent selector appears to remain on the previous selection, but in fact the selected value reverts to the default.

/cc @mikeadamo1

**Comment by dchandekstark** [comment]
Upgrading to select2 v4.0.2 (from 4.0.0) did not appear to solve the issue.

**Comment by seanaery** [comment]
I'm taking a look at this one. Probably will be able to report back tomorrow.

**Comment by dchandekstark** [comment]
Thanks! @seanaery
