### ISSUE TITLE
Enable repository-level lock

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1726]
We currently have functionality that enables repository objects to be locked on a one-by-one basis.  It would be useful, I think, to be able to lock the repository as a whole (essentially set it to read-only) without have to lock each object individually.  I envision this lock as being independent of individual object locks ... i.e., an object is considered locked if the repository is locked or if the object itself is locked.  (Correspondingly, an object is considered unlocked if the repository is not locked and the object itself is not locked.)

**Comment by coblej** [comment]
@dchandekstark @jt112 Does this seem like a good idea to you?

**Comment by dchandekstark** [comment]
Maybe. What did you have in mind for implementation?

**Comment by coblej** [comment]
Haven't thought about it deeply but, off the top of my head, a config setting.  `locked?` is now defined as `!!is_locked` ... could be defined as `repo_locked? || !!is_locked` (where `repo_locked?` queries the config setting).

**Comment by dchandekstark** [comment]
Moved to Jira.
