### ISSUE TITLE
Link from object page to fcrepo admin view

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1743]

**Comment by dchandekstark** [comment]
Suggest simply displaying the LDP source graph:

```ruby
obj.ldp_source.graph.dump(:ttl)
```

**Comment by jt112** [comment]
Would you mind providing an example value for that field, please?

Jim Tuttle
Head, Digital Repository Services
Duke University Libraries
919.613.6831

On Jul 7, 2016, at 12:16, David Chandek-Stark <notifications@github.com<mailto:notifications@github.com>> wrote:


Suggest simply displaying the LDP source graph:

obj.ldp_source.graph.dump(:ttl)

**Comment by dchandekstark** [comment]
@jt112 The idea would be to show a "raw" view of the Fedora object -- analogous to showing the FOXML in Fedora 3.  Originally I had been thinking there would simply be a link from the staff UI to the Fedora admin UI for that object, but I think it's better to display it directly in dul-hydra.  I expect this would only be useful to repository administrators.

**Comment by dchandekstark** [comment]
Moved to Jira.
