### ISSUE TITLE
Web widget to walk directory tree representation

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1756]
There are a couple of cases (e.g., DPC Folder Ingest, Simple Ingest) where it would be useful to have a web form control that, given a starting path on server-mounted storage, allows the user to walk the directory structure from that point downwards and select a folder or file.  It may, in fact, be better for this widget to handed a nested representation of the directory structure (rather than have raw view of the actual storage) so that we can control the paths and selections that a particular user can make.

**Comment by dchandekstark** [comment]
Moved to Jira.
