### ISSUE TITLE
Additional author/creator information

### ISSUE THREAD

**Issue by jt112** [duke-libraries/dul-hydra#263]
Several authors and creators of data sets have asked that we allow them to associate authors with institutions.  DSpace allows one or more author fields and one or more organizational-group fields but no way to correlate the author to the institution.  I'd like to look into how we might address that so that we can say Author: Jim Coble, Duke University; Author: Someone Else, Somewhere Else.

**Comment by dchandekstark** [comment]
@coblej @jt112 We should explore how we can mix and match literal author values ("Jim Tuttle") and structured author values (URI or internal triples).  This is obviously a complicated issue that needs study and recommendation.

**Comment by dchandekstark** [comment]
@jt112 We need user stories and prioritization for this issue.

**Comment by dchandekstark** [comment]
Re-create in Jira as desired.
