### ISSUE TITLE
Select thumbnail for Collection / Item

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#691]
A user with edit permission on a Collection should be able to select its thumbnail from among those of its child Items (and/or the child Components of those Items?).
A user with edit permission on an Item should be able to select its thumbnail from among those of its child Components.

Should a user with edit permission on a Collection / Item also be able to upload an arbitrary image (of appropriate size) as that Collection's / Item's thumbnail?  If the answer to this is yes, one possibly simple implementation of this functionality would be to do just the arbitrary thumbnail upload.  To use a thumbnail from a child object, the user would download the thumbnail from the child / grandchild (browser "save as") and upload it to the Collection / Item.

**Comment by dchandekstark** [comment]
@jt112 @coblej removed milestone pending further consideration and prioritization.

**Comment by dchandekstark** [comment]
In order to implement this in the quickest way on the Fedora 3-based app, I am adding two Rake tasks, `dul_hydra:thumbnail:copy[source_id,target_id]` and `dul_hydra:thumbnail:upload[file,target_id]`.
