### ISSUE TITLE
Set parent thumbnail from child if parent thumbnail missing

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#733]
Given that a parent object has no thumbnail set,
when a child object with a thumbnail is added to that parent,
the parent thumbnail should be set to that of the child.

Currently, these conditions would be met only in the case of a Component being added to an Item.

Question for consideration: When a parent object gets a thumbnail, should it check to see if it has a parent without a thumbnail and, if so, similarly set its parent's thumbnail.  Currently, this would apply in the case of an Item getting a thumbnail from a Component and the Collection to which the Item belongs not having a thumbnail.

**Comment by dchandekstark** [comment]
@coblej ping

**Comment by dchandekstark** [comment]
@coblej Issue is 2.5 years old -- dead?
