### ISSUE TITLE
Re-evaluate / re-work batch validation as separate step

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#764]
To address https://github.com/duke-libraries/dul-hydra/issues/760, the requirement (and capability) to validate a batch prior to submitting it for processing was temporarily removed.  This is not particularly detrimental since a batch submitted for processing first performs its own validation.

The requirement / option to validate a batch prior to submitting it for processing should be re-evaluated and, if the functionality is to be retained, it needs to be re-worked.  Another the issues to be considered are
- should it be required or simply an option
- should it be run in real-time while the user waits or submitted to a background job processor
- how to display validation errors to the user, especially if it is run in real-time and there are hundreds or thousands of objects in the batch

**Comment by dchandekstark** [comment]
@coblej This is pretty old. Still relevant?

**Comment by jt112** [comment]
@dchandekstark I think it is.  It may prevent a lot of wasted time and frustration on the part of the depositor to know that the batch is going to fail in 2 minutes rather than hours or days.

**Comment by coblej** [comment]
@jt112 @dchandekstark Unfortunately, the validation process as it currently exists doesn't fail "in 2 minutes" ... for a batch of any appreciable size, it may take hours to run the validation step.  I'm going to close this for now in deference to future work on batch processing.
