### ISSUE TITLE
encrypted Office files detection

### ISSUE THREAD

**Issue by laissezfarrell** [duke-libraries/dul-hydra#900]
As per Winston's link, Apache Tika or similar application  would detect when an encrypted office file is submitted.

Students submitting ETDs to DukeSpace have submitted encrypted Excel documents in the past, and it is possible that born-digital archival holdings may include encrypted files.

**Comment by dchandekstark** [comment]
I would suggest wrapping this into a comprehensive file characterization regime. @jt112

**Comment by jt112** [comment]
Sounds reasonable.  Do you happen to know if any of the tools that FITS integrates with can identify encrypted files?

**Comment by dchandekstark** [comment]
I believe that recent versions of FITS incorporate tools with this capability, but need to confirm.

**Comment by WinstonAtkins** [comment]
In addition to Tika, you might be interested in "Tools for identifying obfuscated files, specifically password protected and encrypted formats?" from Digital Preservation Q&A: http://qanda.digipres.org/588/identifying-obfuscated-specifically-protected-encrypted.

**Comment by dchandekstark** [comment]
@laissezfarrell It still seems as of this date that catching the Tika EncryptedDocumentException is the best option.

**Comment by dchandekstark** [comment]
Moved to Jira.
