### ISSUE TITLE
Object remote replication and validation

### ISSUE THREAD

**Issue by jt112** [duke-libraries/dul-hydra#910]
A Repository Administrator should have the option to set a per-collection policy describing the remote replication configuration for objects in the collection.  The policy should be multi-tier including non-replicating and replicating to one of two or more remote spaces.  For example, a collection may not be replicated, may be replicated to DuraSpace, or may be replicated to Digtal Preservation Network.  The administrative metadata for the object should reflect the replication tier and status. Status should inform Collection Curators of replications location and status.  Status should explain if an object is replicated and if the replication has verified by comparing checksum, and and date of last validation. 

Replication should be handled transparently and automatically.  Objects should be versioned in the replication space.  Restoration of replication objects is out of scope.   The architecture of the replication space is an open question- it may be a CIFS space, shell access, or a replica of our Fedora repository.

**Comment by dchandekstark** [comment]
@jt112 @coblej Removing milestone as I don't think we've scoped this issue sufficiently to tie it to a release target.

**Comment by dchandekstark** [comment]
Moved to Jira.
