### ISSUE TITLE
Submitting empty rights form raises uncaught exception

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#913]
Submitting a Permissions or Default Permissions form (_rights_form.html.erb) with no values in the fields raises an uncaught exception is rights_behavior or policy_behavior, respectively.

16:02:01 INFO: Completed 500 Internal Server Error in 31ms 
16:02:01 FATAL: 
NoMethodError (undefined method `fetch' for nil:NilClass):
  app/controllers/concerns/dul_hydra/controller/rights_behavior.rb:15:in `block in permissions'
  app/controllers/concerns/dul_hydra/controller/rights_behavior.rb:14:in `each'
  app/controllers/concerns/dul_hydra/controller/rights_behavior.rb:14:in `permissions'

15:58:35 INFO: Completed 500 Internal Server Error in 30ms 
15:58:35 FATAL: 
NoMethodError (undefined method `fetch' for nil:NilClass):
  app/controllers/concerns/dul_hydra/controller/policy_behavior.rb:16:in `block in default_permissions'
  app/controllers/concerns/dul_hydra/controller/policy_behavior.rb:15:in `each'
  app/controllers/concerns/dul_hydra/controller/policy_behavior.rb:15:in `default_permissions'

**Comment by coblej** [comment]
@dchandekstark This seems to have been fixed when submitting an empty Permissions form but not when submitting an empty Default Permissions form.  When I submit an empty Default Permissions form, I get the error below.  I don't know that it's worth holding up the release 3.1.0 for this but we should probably fix it eventually anyway.

```
08:47:18 FATAL: 
ActionController::ParameterMissing (param is missing or the value is empty: permissions):
  app/controllers/concerns/dul_hydra/controller/policy_behavior.rb:31:in `default_permissions_params'
  app/controllers/concerns/dul_hydra/controller/policy_behavior.rb:9:in `default_permissions'
```

**Comment by dchandekstark** [comment]
Rights form is gone with role based authz.
